remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Dominika A. DÅ‚ugosz
description: PhD Student in AI
show_downloads: true
logo: /assets/prof.jpg
google_analytics: G-TPKB5JRRVG

github:
  zip_url: /assets/CV_DDlugosz.pdf
  tar_url: https://orcid.org/0009-0003-9303-1120
