remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Dominika A. Dlugosz
tagline: AI PhD Student
description: Personal page
show_downloads: false
google_analytics: G-TPKB5JRRVG
