remote_theme: pages-themes/midnight@v0.2.0
plugins:
- jekyll-remote-theme

title: Dominika A. DÅ‚ugosz
description: PhD Student in AI
show_downloads: false
logo: /assets/prof.jpg
google_analytics: G-TPKB5JRRVG

